[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Cross-platform library for managing passwords"
homepage = "https://github.com/hwchen/keyring-rs.git"
keywords = ["password", "cross-platform", "keychain", "keyring"]
license = "MIT OR Apache-2.0"
build = "build.rs"
name = "keyring"
repository = "https://github.com/hwchen/keyring-rs.git"
version = "0.7.1"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.3.0"

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "1.0.0"

[target.'cfg(target_os = "windows")'.dependencies]
byteorder = "1.2.1"
winapi = "0.3.8"

[dev-dependencies]
clap = "2.0.5"
rpassword = "2.0.0"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"
